modLoader = "javafml" #mandatory
loaderVersion = "[4,)"
license = "All Rights Reserved"
[[mods]] #mandatory
modId = "moonstone_dna" #mandatory
version = "1.1.9.7-neoforge" #mandatory
displayName = "Moonstone-DNA" #mandatory
authors = "Ytgld}" #optional
description = '''${mod_description}'''

[[mixins]]
config = "moonstone_dna.mixins.json"

[[dependencies.moonstone_dna]]
modId="neoforge"
type="required"
versionRange="[21.0.28-beta,)"
ordering="NONE"
side="BOTH"
[[dependencies.moonstone_dna]]
modId="minecraft"
type="required"
versionRange="[1.21, 1.22)"
ordering="NONE"
side="BOTH"